### ISSUE TITLE
from_name & from_email errors result in strange feedback

### ISSUE THREAD

**Issue by Puddingboy** [bolt/boltforms#100]
In my case it kept showing me issues in validation and fields while the issue was that the variable assigned to from_email didn't point to an existing field within that specific form. The issue arose when I made quite a few forms and ended up editing the forms after a few weeks.  Maybe you could take a look into it. I will check later today and try to add some more details as to what errors I get.

**Comment by GawainLynch** [comment]
Have you tried the `ev-master` version as well?  The extension has been heavily rewritten there.

**Comment by Puddingboy** [comment]
I am not sure, I will check this out a bit later as I have other small stuff to do. I will let you know as soon as possible.

**Comment by GawainLynch** [comment]
The feedback handling has been redone in master, so closing for now … you know who to nag if there is further problems  :wink:
