### ISSUE TITLE
Key "datepublish" does not exist

### ISSUE THREAD

**Issue by nestordedios** [bolt/boltforms#102]
Hi @GawainLynch ,

After submitting a form I get an email with the error below when I have strict_variables set to true and debug_error_level set to 8181:

**Key "datepublish" in object with ArrayAccess of class "Bolt\Extension\Bolt\BoltForms\Config\FormConfigSection" does not exist**

With strict_variables set to false and debug_error_level set to -1 I get a succeed email.

The data submitted in the form is saved in the database as a record of a contenttype.
```
database:
    contenttype: name-of-the-contenttype
```

It doesn't seem to be a critical error, just something you can look into when you have time or you are bored :stuck_out_tongue_winking_eye: to get rid of the annoying error message.

**Comment by GawainLynch** [comment]
Old version … blame the :hamster: 

:stuck_out_tongue_winking_eye:
