### ISSUE TITLE
Simple question: how do you get a specific field into the email template

### ISSUE THREAD

**Issue by evertalbers** [bolt/boltforms#104]
I expected that 
`<p>Geachte {{ name }},</p>` or
`<p>Geachte {{ form.name }},</p>`
would work when **name** is a field in the form, but apparently this should be another value.

**Comment by GawainLynch** [comment]
This is the in-flight dump of the Twig variables:
![image](https://cloud.githubusercontent.com/assets/1427081/18229880/dff86ce0-7289-11e6-8e17-4a3cb43a0078.png)

So in the email template, you have a variable called `data` that contains the array of values from the form.

**Comment by evertalbers** [comment]
Thanks! 

Maybe put a `{{ data.name }}` somewhere in https://github.com/bolt/boltforms/blob/master/templates/email/email.twig to put people on the right track?

And it's only after I read your reply, that I realised that you can put a `{{ dump(data) }}` `{{ dump(fields) }}` and `{{ dump(config) }}` in an email template, so you might mention that somewhere, too.

**Comment by GawainLynch** [comment]
I don't suppose you'd be talked into adding something "front-ender friendly" to the broken-out docs for the upcoming release: https://github.com/bolt/boltforms/tree/master/doc :smile:

**Comment by evertalbers** [comment]
The first thing that I'd suggest is making separate small pages in the docs for email, subject, form and files. I could make a start for the first two, not sure about the form and I better stay away from the file upload.

For when are the BoltForms launch and TV marketing campaign scheduled? (he asked worryingly)

**Comment by GawainLynch** [comment]
Launch … as our friends at Blizzard would say, "When it is ready" … but soon(ish) … and it is overdue.

I'll try this week(end?) to start laying out some doc files/directories.

**Comment by GawainLynch** [comment]
Closing as part of a clean up. Feel free to re-open if needed.

A while ago I added more comments to the base templates that detail what parameters are available, and a lot of the `docs/` directory is in better shape now … need more time in my day :laughing:

**Comment by evertalbers** [comment]
Thanks! Same thing here...  I am painfully aware that I still wanted to have a look at these pages.
