### ISSUE TITLE
Bolt Multisites FileUpload wrong database

### ISSUE THREAD

**Issue by kouz75** [bolt/boltforms#106]
Hi.

We are using bolt in multisites mode (https://docs.bolt.cm/3.1/howto/multi-site-setup).
We have create a form to upload a file to bold and save it in a entity.

The file is store correctly in the folder set in the config file of BoltForm.
The entity is record in the DB.
But the image name is the DB is set to a wrong value :
 on linux /tmp/phpRANDOMSTRING 
on macos /private/var/tmp/phpm1yURZ
I think the folder is link with my php setting.

If I use the same form in a basic Bolt website, everthings works fine.

thanks for your help

**Comment by GawainLynch** [comment]
What version of BoltForms?

**Comment by kouz75** [comment]
sorry for the ticket, someone have do wrong stuff with the StorageEvent ...

**Comment by GawainLynch** [comment]
Zero stress mate :+1:
