### ISSUE TITLE
Accessing field label

### ISSUE THREAD

**Issue by nlemoine** [bolt/boltforms#110]
Field label are part of the options array from `FieldOptions` and are private: 
https://github.com/bolt/boltforms/blob/master/src/Config/FieldOptions.php#L44

They can't be accessed from the email template: https://github.com/bolt/boltforms/blob/master/templates/email/email.twig#L17

I don't really know how you want to deal with this, make the options array public? Provide a public method such as `getOptions` to enable access to options?

**Comment by GawainLynch** [comment]
Refactoring that class is one of the last on my TODO list … watch this space :smile:

**Comment by GawainLynch** [comment]
Fixed in #111 via 463d8d9ac00ab26eafb5e7d3ad13f4d74752e90a

**Comment by GawainLynch** [comment]
Updated approach in #113 to config and those variables … :koala: did it first time :wink:

**Comment by nlemoine** [comment]
👍
