### ISSUE TITLE
Should we decide a cc email address is empty before setCc?

### ISSUE THREAD

**Issue by everyx** [bolt/boltforms#112]
In https://github.com/bolt/boltforms/blob/bolt-2/src/Email.php#L208

I have used v2 in my project, and set `cc_email` in `boltforms.bolt.yml` to bind a item in form, and sometimes the item value is empty, and I think in this case, the email should not be sended to the cc_email address.

**Comment by GawainLynch** [comment]
This has been completely rewritten in 4.0.0-beta and if the parameters are not set it won't try to add them
