### ISSUE TITLE
Invalid class?

### ISSUE THREAD

**Issue by Puddingboy** [bolt/boltforms#116]
On latest version of bolt:
![backand response](http://puu.sh/rPtrj/9ead1370e4.png)

Currently bolt translate is also in use. I wonder if that would be the source of this problem tho

**Comment by GawainLynch** [comment]
Running (and working) on nearly every site we have. That error occurs when the Composer autoloader can't find the class … so I'd try uninstalling and reinstalling.

**Comment by Puddingboy** [comment]
Oh that fixed it. Any idea why that happens and how I can prevent it in the future?

**Comment by GawainLynch** [comment]
Not really … that is all off in Composer Land at that point … plus if you have an intermittent or unexpected timeout over the network it can still fail.
