### ISSUE TITLE
Ajax not working

### ISSUE THREAD

**Issue by michelangeloRome** [bolt/boltforms#120]
Hi,
I'm installed latest boltforms from Bolt Store and loaded jquery (available as jquery.min.js).
I have enabled ajax but my forms still submit not using ajax and i'll get redirected.

Am i missing something?

This is my cfg

```
test_save:
  submission:
      ajax: true
  feedback:
    success: Message submission successful
    error: There are errors in the form, please fix before trying to resubmit
#  database:
#    contenttype: adv_stats  # ContentType record to create
  fields:
    adv_seen:
      type: integer
      options:
        required: true
        label: Num adv
        attr:
          placeholder: num adv
        constraints: [ NotBlank ]
    phone_seen:
      type: integer
      options:
        required: true
        label: Num phone
        attr:
          placeholder: num phone
        constraints: [ NotBlank ]
    submit:
      type: submit
```

**Comment by GawainLynch** [comment]
The AJAX functionality is only available in the `master` branch, that will be come BoltForms v4.x … and is still very much work in progress.

If without modifying your setup, you've installed via the market place, you will have v3.x (probably 3.1.0) and that does not have this feature.

**Comment by michelangeloRome** [comment]
Oh, forgive me for my disattention.
I'm going to try master branch. I'll try this beta function, maybe I can help :)

Thank you very much

**Comment by GawainLynch** [comment]
Zero stress, it is easy done. :smile: 

Just bear in mind that master is not considered "stable" just yet, but patience and PRs are most welcome around here :+1:
