### ISSUE TITLE
Question about yml vs templates

### ISSUE THREAD

**Issue by Puddingboy** [bolt/boltforms#121]
in templates you can use Overwrite: { fields { props: { } } }.

Is the extension built so that `overrides` will completely override the yml properties or will the field still hold the same constraints and filters for overwritten fields? Or at least, What is intended behavior for this extension?

I have a setup where being able to fiddle with templates is a better idea than editting the yml files.  Getting a better understanding would sure help.

**Comment by GawainLynch** [comment]
Gory details [are here](https://github.com/bolt/boltforms/blob/master/doc/templates.md#configuration-overrides) but note that this is only available in master at the moment, I am nearly done with the v4 work, but time.

Short version though, the override gives you run-time control over what is defined in YAML.
