### ISSUE TITLE
Path / {{webpath}} to boltforms.css does not start with '/'

### ISSUE THREAD

**Issue by anketwokings** [bolt/boltforms#133]
The css path looks like it's not defined from the root.

When loading the css from something other then a page, it will attempt to load it from site/entry/123/extensions/vendor/etcetcetc...

I can of course override the boltforms_form.twig template, en manually put a '/' in, but it would be more logical if that would be the default.

Thx!

----------
Version 3.1.0

**Comment by GawainLynch** [comment]
Fixed in 449bc890e32144480259f3ee99fa2f78d73688f5 and will add to the next 3.x release if there is one (I had caught it in master already).

**Comment by anketwokings** [comment]
Thanks! Lodewijk suspected it was already fixed in the newer version, but this is the one that Bolt suggested me to download. :)

**Comment by GawainLynch** [comment]
Yeah, I haven't tagged BoltForms 4.0 yet, as we're tidying it up in that thing that you, Lodewijk & I are working on … making sure all the bits fit where they're supposed to, 'n stuff.

**Comment by jamieburchell** [comment]
I see this is fixed in the 3.1 branch, but composer is bringing down the file without the fix applied?

composer.json:

`"bolt/boltforms": "^3.1",`

`extensions\vendor\bolt\boltforms\templates\boltforms_form.twig:`

`<link href="{{ webpath }}/boltforms.css" rel="stylesheet" type="text/css" />`
