### ISSUE TITLE
Settings data for checkboxes

### ISSUE THREAD

**Issue by michelangeloRome** [bolt/boltforms#136]
Hi all,
I'm trying to pass parameters to BoltForms to have a prefilled form like follows:

{{ boltforms('test_save', defaults=param) }}

But I can't figure out how to set checkboxes values. Where can I find some infos?

Thx

**Comment by GawainLynch** [comment]
Greetings, @michelangeloRome :wave: 

The documentation for that field type is here: http://symfony.com/doc/current/reference/forms/types/checkbox.html

BoltForms just implements Symfony Forms, so the Symfony site is the best reference for field options themselves.
