### ISSUE TITLE
CSS error 404

### ISSUE THREAD

**Issue by NodokaMurmevent** [bolt/boltforms#137]
Bolt 3.2.5.
BoltForm 3.1.0

In the profiler BoltForm search boltforms.css at the wrong path : 
``404   GET    [install folder]/public/page/extensions/vendor/bolt/boltforms/boltforms.css``

if i look for him, i found him here : 
[install folder]/public/page/extensions/vendor/bolt/boltforms/**web**/boltforms.css

**Comment by GawainLynch** [comment]
This is fixed in 4.0.0-beta1

A note on beta releases, I just submitted a bug fix https://github.com/bolt/bolt/pull/6279 for the Extend page to show pre-release versions, but using Composer on the command line does work.
