### ISSUE TITLE
Docs issue - no email command in app/nut?

### ISSUE THREAD

**Issue by thely** [bolt/boltforms#138]
On DreamHost, excited to be in the finishing stages on my portfolio site, trying to figure out what's going wrong with my SMTP config. I noticed that the `email` command doesn't exist in Nut. Is it something BoltForms tacks on? When I run `./app/nut email:spool --show` as in `docs/email.md`, I get `There are no commands defined in the "email" namespace.`

**Comment by SahAssar** [comment]
I think that's just in the 4.0 version, which is yet to be released. Install the beta if you want to check it out.
