### ISSUE TITLE
Are plain arrays no longer valid in 4.0 beta ?

### ISSUE THREAD

**Issue by zomars** [bolt/boltforms#154]
I had this in a choice field: `choices: [ 'foo', 'bar' ]` but It renders as 0, 1 in the front end.

I don't know if this is the intended behaviour and I'm aware of hashes, I just want to know if this is intended.

**Comment by Puddingboy** [comment]
I ran into the same thing a couple of times over the past years. I am tempted to think this is actually according to spec. Often regular arrays are represented and interprented as `{0: value1, 1: value2, etc, etc}`, so you are actually submitting the the index as the value while your value becomes the keyword.

To make this a bit more convenient you can choose to write it in an object notation
```
choices: {option value: option content, etc}
```
or you can write it like
```
choices:
    option-value1: optionInnerText
    option-value2: optionInnerText
```

I always prefer the second style

**Comment by rossriley** [comment]
This is due to an underlying change with Symfony forms, the correct way now is like this in php:

```
'choices'  => array(
        'Maybe' => null,
        'Yes' => true,
        'No' => false,
    ),
```

and in yml:

```
choices:
    'Maybe': null
    'Yes': true
    'No': false
```
