### ISSUE TITLE
[BoltForms 4] Ajax functionality not working when logged out

### ISSUE THREAD

**Issue by Matthewbeck75** [bolt/boltforms#166]
When using a browser that is not logged in to Bolt, the forms cannot be used if they are set to ajax: true.

On submission, a 400 Bad Request is returned, along with the following response:

    JSON	
    0	"Invalid compiler"   

The error appears to be coming from here https://github.com/bolt/boltforms/blob/28d0416414e760793f469a34d6995f58a3131eb7/src/Controller/Async.php#L73

The error is not encountered when logged in, or when turning Ajax off.

## Reproduction

Install Bolt 3.2.14
Bolt Forms 4.0.0
Set minimum-stability to beta in config.yml
add_jquery: false though jquery is added elsewhere in the page
Server type: Nginx/1.10.0 (Ubuntu)

## Other info

PHP version: 7.0.15

Debug log when attempting to submit Ajax form on logged out browser: https://pastebin.com/UjAeYpBe
boltforms.bolt.yml: https://pastebin.com/SRzaX3v1 (email addresses removed)

Request Params: 

    
```
Query string	
form	"contact_Hove"
Form data	
contact_Hove[name]	"matt"
contact_Hove[email]	"example@example.com"
contact_Hove[number]	""
contact_Hove[message]	"test"
contact_Hove[_token]	"GXp0f0CidST__Xg2uTZRL5mh8WiwpiTsWmCvieowuKI"
contact_Hove[submit]	""
```

**Comment by rossriley** [comment]
We did already have a fix in for this issue but it hadn't made it into a release. I've just tagged and published 4.1 if you could upgrade and test then let me know if you're still seeing any issues.

**Comment by SahAssar** [comment]
Just helped another person on slack with the same issue, and it was solved by upgrading so I think this can be considered solved :)

**Comment by ghost** [comment]
Hi!
I'm using BoltForms 4.3.1 and I have exact the same issue. When logged in, I can use the form without problems. When logged off, I get the error mentioned by Matthewbeck75 in his initial post.
