### ISSUE TITLE
database/table option not working

### ISSUE THREAD

**Issue by svivian** [bolt/boltforms#173]
I noticed there is the `database` option in the boltforms config, but I cannot get it to work. Can't find any documentation. I have this on my form:

    database:
      table: boltforms_contact    # Specific database table to write to

I've created a table `boltforms_contact` and added 4 field that match my form (name, email, phone, message). But when I submit the form nothing is added to the database. I don't get any errors, it says "Message submitted successfully".

Is there some other format the table need to be in? I tried adding an `id` field as a primary key but still nothing gets added.

**Comment by nestordedios** [comment]
In [DatabaseTable.php#L64](https://github.com/bolt/boltforms/blob/master/src/Submission/Handler/DatabaseTable.php#L64), it does:

```
$formData->has($colName)
```

`$formData` is of the following types:

- `Bolt\Extension\Bolt\BoltForms\Form\Entity\Content`
- extends `Bolt\Storage\Entity\Content`
- extends `Bolt\Storage\Entity\Entity`
  - has `Bolt\Storage\Entity\MagicAttributeTrait`

In [MagicAttributeTrait#122](https://github.com/bolt/bolt/blob/3.3/src/Storage/Entity/MagicAttributeTrait.php#L122), it says `has` is `protected` (which makes sense).

So I believe the has function call needs to be something different, like:

```
if (isset($formData[$colName])) {
```

**Comment by rossriley** [comment]
Fixed in v4.1.5
