### ISSUE TITLE
Label option mandatory when it shouldn't be

### ISSUE THREAD

**Issue by lenvanessen** [bolt/boltforms#183]
So this is what is happening. When you have a form, and you don't specificly define a label for the field, it should default to the fieldname.

As you can see here:
https://github.com/bolt/boltforms/blob/master/templates/email/_blocks.twig#L4

But as you can see here it throws an exception when the field is not found
https://github.com/bolt/boltforms/blob/master/src/Config/Form/FieldOptionsBag.php#L92

So the twig template can never default back to the fieldname, since an exception in thrown.

**Comment by bobdenotter** [comment]
Fix in the Queue at #207

**Comment by rossriley** [comment]
Merged
