### ISSUE TITLE
Feedback Error Message Appears in messages.debug Instead of messages.error 

### ISSUE THREAD

**Issue by saltpeanuts** [bolt/boltforms#187]
`boltforms.bolt.yml` has two feedback options.

```
feedback:
        success: Message submission successful
        error: There are errors in the form, please fix before trying to resubmit
```

If the form is submitted successfully the `success:` message appears in the `messages.info` array.

If the form has validation errors I'd expect to find the `error:` message in `messages.error`, so this message can be displayed above the invalid form.

Instead this appears in the `messages.debug` array.

BoltForms v4.1.9 / Bolt 3.3.3

**Comment by tricksel** [comment]
I have the same problem on Bolt 3.4.5/BoltForms 4.1.14.

**Comment by tricksel** [comment]
Found the solution.

in extensions/vendor/bolt/boltforms/src/Twig/Extension/BoltFormsRuntime.php on line 282 AND 285, replace this:
`$this->message(Processor::FEEDBACK_ERROR, $e->getMessage());`
with this
`$this->message($e->getMessage(), Processor::FEEDBACK_ERROR);`

Variables are in the wrong order.

**Comment by rossriley** [comment]
@tricksel thanks for that, we'll get a fix in the next release.
