### ISSUE TITLE
Fieldtype Repeater

### ISSUE THREAD

**Issue by Ichag** [bolt/boltforms#188]
Hi,
is it possible to use the fieldtype "repeater" as a boltforms fieldttype?
If not, what has to be done to make it usable?

**Comment by rossriley** [comment]
It's important to note that BoltForms integrates the Symfony Forms API with a Bolt Frontend and so doesn't share any of the same code as the backend UI you see when logging into Bolt.

The one place where they do intersect though is if you save the results of a BoltForm to a contenttype and if one of the fields in your contenttype is a repeater then this will work correctly, assuming your form is an array of sets of fields.

In terms of rendering the form, you would have to take care of the UI to do so, but assuming the end result was an array of sets of fields then the insert would work.
