### ISSUE TITLE
PR #168 is gone in 4.1

### ISSUE THREAD

**Issue by lenvanessen** [bolt/boltforms#191]

**Comment by rossriley** [comment]
Looks ok to me, I just did a merge of the commit but there was no diff and the location code seems to be in there ok... eg: https://github.com/bolt/boltforms/blob/4.1/templates/form/form.twig#L74

**Comment by lenvanessen** [comment]
Yeah, Looking at it now it's there, But was missing in 4.1.1 (even though it was merged against 4.1) But that's already sorted:)

--
Len van Essen

Op 12 september 2017 om 23:08:30, Ross Riley (notifications@github.com<mailto:notifications@github.com>) schreef:

Looks ok to me, I just did a merge of the commit but there was no diff and the location code seems to be in there ok... eg: https://github.com/bolt/boltforms/blob/4.1/templates/form/form.twig#L74
