### ISSUE TITLE
Undefined method "getClientOriginalName" with attach files

### ISSUE THREAD

**Issue by jasperjorna** [bolt/boltforms#196]
When attaching an uploaded file to an email with `attach_files: true` it throws an undefined method exception:

```
UndefinedMethodException in Email.php line 289: 
Attempted to call an undefined method named "getClientOriginalName" of class "Bolt\Extension\Bolt\BoltForms\Submission\File".
```

Looks like it was introduced here: https://github.com/bolt/boltforms/commit/8c34d0fb44e7b42d042c9fbd0dd237e978c7615f

**Comment by anketwokings** [comment]
Great! I was just making an issue for this, when I saw it was _already_ fixed 21 hours ago! Thank you!!
