### ISSUE TITLE
Display one question at a time.

### ISSUE THREAD

**Issue by thomasboxall** [bolt/boltforms#212]
I have a unique design requirement from a client.  They want to present the questions in the form one question at a time.  Is it possible to do something like this?

{{ boltforms('my_form', quest001) }}

Where my_form is the name of my form I'm submitting, and quest001 is the name of the question I want to display.

**Comment by bobdenotter** [comment]
This is currently not possible using Boltforms. In fact, this looks like something you'd probably be better off using TypeForm.com for, and then embedding that in the page.

**Comment by rossriley** [comment]
@thomasboxall it occurred to me that if you are saving a form to a contenttype then there's no requirement to save all the fields as long as you include the id as a hidden field. So you could make a form with multiple questions as fields and then have a template that decides which question to show.

I've not tried it and you might need to do a bit of custom coding but it should be doable if you have a bit of time to develop/test.
