### ISSUE TITLE
[bug] Field delete button not working

### ISSUE THREAD

**Issue by eduardomart** [bolt/boltforms#221]
The trashcan icon [delete] doesn't seem to be working. 

See demo here:
https://monosnap.com/file/OnEXtFMxayp4mSCjvMHFQrJuwWhOnp

---
Bolt 3.4.3
BoltForms 4.1.14
FormEditor 4.0.2

**Comment by SahAssar** [comment]
I think this is a bug with FormEditor, not BoltForms.

**Comment by eduardomart** [comment]
OMG, you're right, sorry :(
