### ISSUE TITLE
[bug] Error when trying to edit a form

### ISSUE THREAD

**Issue by eduardomart** [bolt/boltforms#222]
I have a form that I created in BoltForms manually, it has 3 simple fields: Name, Email, Message

After Installing Bolt Forms I can see it in there:

---
![screen shot 2017-12-10 at 12 59 57 pm](https://user-images.githubusercontent.com/1833020/33809334-13ca2572-ddaa-11e7-8c23-77d7e891996f.png)
---
However, if I try to edit it I get this error:

---
![slack-imgs](https://user-images.githubusercontent.com/1833020/33809319-e81201e8-dda9-11e7-8d7d-3b9549b87fac.png)
---
New forms that I create within FormsEditor can be edited though

---
Bolt 3.4.3
BoltForms 4.1.14
FormEditor 4.0.2

**Comment by SahAssar** [comment]
I think this is a bug with FormEditor, not BoltForms.
