### ISSUE TITLE
Form constraint errors not being translated

### ISSUE THREAD

**Issue by Largo** [bolt/boltforms#23]
So. I have a form with constraints.
A not blank constraint gets the error 'This value should not be blank' instead of a translated one.
Silex apparently has the german translations for this. 
When I set the locale: 'de' instead of 'de_DE' in the bolt config, the value is translated, but the bolt backend isn't translated anymore. :(

I'm not sure how to fix this properly. Maybe you can change the fallback locale to the first part of the whole locale.

**Comment by Largo** [comment]
Quickfix: inserting $this->app['locale'] = 'de'; into the constructor of BoltForms.

**Comment by GawainLynch** [comment]
Yeah, this is mildly problematic… and is actually a Bolt bug as the locale *should* fall back to the two letter version.

**Comment by GawainLynch** [comment]
That said, let me see what I can do here as I thought Symfony handled ISO locale codes properly.

**Comment by GawainLynch** [comment]
ping @rarila

**Comment by rarila** [comment]
I also thought it would [handle this automatically](http://symfony.com/doc/current/book/translation.html#book-translation-fallback).
Question is, where does this translation come from. Probably the translations have to be added to bolts own xlf. Other than that I'm in Schultz-mode when it comes to symfony forms.

**Comment by GawainLynch** [comment]
@rarila yeah, it's kinda tricky, it assumes what's in `$app['locale']`

**Comment by SkillyWeb** [comment]
Any news ?

**Comment by tameroski** [comment]
No update on that issue ? Still using @Largo 's hotfix, but editing a plugins source file is not my kind of stuff.

**Comment by GawainLynch** [comment]
There is not much the extension itself can do… it is reliant on Bolt itself.

**Comment by xstable** [comment]
Also stuck on this today. Dirty-Hack works. Hope I remember where to set it, if the extension will be upgraded :)
Will this be fixed in bolt3 ?

**Comment by xstable** [comment]
Maybe a better workarround as suggested by Largo:
Read the default-Format, and slice it to the two letter one: 
```
        if(strlen($this->app['locale'])>2){
            $this->app['locale'] = substr($this->app['locale'],0,2);
        }
```

**Comment by GawainLynch** [comment]
@xstable that will override the locale settings for the entire application
