### ISSUE TITLE
Using a no-required field in from, to, cc etc gives unexpected results

### ISSUE THREAD

**Issue by anketwokings** [bolt/boltforms#237]
When you use user submitted data in the to, from, cc or bcc fields and you insert a non-required field that is not filled out by the user, it behaves unexpected. 

## How to reproduce
- Make a form
- fields are: `firstname`, `preposition`, `lastname`
- Address the form to : 
``` 
subject: "Confirmation of registration"
from_name: [firstname, preposition, lastname]
from_email: email
to_email: <insert your email here>
```
Now use the form as 'Robin of Loxley' (and use 'of' as the preposition). 
Result -> ``from_name = 'Robin of Loxley'`` (no problem)

Now use the form as 'Robin Hood' 
Expected -> ``from_name = 'Robin Hood'`` 
Result -> ``from_name = 'Robin preposition Hood'``

## So what happens:
When an empty field ( in this case a non-required field) is used, it literally returns the **label**.

## Preferred behaviour:
If the field is left empty, it should return no value, and leave it empty.

## disclaimer:
I use 'preposition (dutch: voorvoegsel') here, in the absence of a better example, but of course it occurs with all non-required fields. Saying 'we don't have that kind of last names where I live so the issue is invalid' automatically disqualifies you. ;)

**Comment by jadwigo** [comment]
Adding to that -- if none of the fields are filled (you might not have a surname as a required field) the from name should revert to only the emailaddress in the from_email and not attempt any placeholders.

**Comment by bobdenotter** [comment]
Note, this is a followup to #206
