### ISSUE TITLE
Boltforms creating duplicate entries

### ISSUE THREAD

**Issue by jamesrarmstrong** [bolt/boltforms#243]
I have a simple form which is posting name, email and phone to a database contenttype. First of all I needed to pass a slug, datecreated and datechanged for it to even save the entries to the database, but now it saves the entries twice in the database (identical entries). Are these known bugs?

Versions:
bolt/bolt: v3.2.14
bolt/boltforms: v4.2.1

**Comment by mung** [comment]
I'm having the same issue. Did you resolve it?
