### ISSUE TITLE
Support user/admin account email in email fields

### ISSUE THREAD

**Issue by lucaslcode** [bolt/boltforms#259]
This would be a great feature. Thanks!

**Comment by jadwigo** [comment]
It is a lot of work to add a connection to the bolt user administration from boltforms, and it would also mean that boltforms would break into the back-end.

What exactly do you want to do with this?

If you want to choose between different users to send an email to it is not hard to make a select field in the form that you can use for this.

If you want a complete list of users from the back-end in boltforms on the front-end that is usually considered a leak of sensitive information, so normally you should not want that. In intranet situations this is not a problem, but even there you might want to check if an alternative option is better.

**Comment by lucaslcode** [comment]
I see, I was just thinking it would remove a step if you're setting up
websites for different people, but you're right, it's a quick change and
probably not worth the payoff!

**Comment by jadwigo** [comment]
Most of the time when you build a form, the recipient will be along the lines of info@example.com and the users will use username@example.com for their accounts in the bolt back-end. In those cases you will have to set the recipient manually in the boltforms configuration anyway.
