### ISSUE TITLE
Twig condition into mail template

### ISSUE THREAD

**Issue by Clement-picot6** [bolt/boltforms#268]
Hello,

I'm having a hard time trying to create twig condition into my mail template.
In the website I'm actually working on, I have two differents forms (which are on two different pages).
One is used to get a quote from the company, the other is used to actually join the company as a supplier.
I'd like to set up a condition that makes my mail template understand which form has been sent to the server, and then return the right mail template with all the informations to the company.

I hope anyone can help me figure out how to do it.

Thank you in advance

**Comment by jadwigo** [comment]
You can set the email template per form, so if you have different forms you don't need to switch inside the email template.
```
my_contact_form:
    templates:
        email:      my_sub_directory/email.twig
        subject:    my_sub_directory/subject.twig

my_other_contact_form:
    templates:
        email:      my_sub_directory/other_email.twig
        subject:    my_sub_directory/other_subject.twig
```
https://bolt.github.io/boltforms/templates.html

**Comment by Clement-picot6** [comment]
Oh I forgot about that !
Thanks a lot ! I close the issue 👍
