### ISSUE TITLE
Chained selectors

### ISSUE THREAD

**Issue by bebetodias** [bolt/boltforms#33]
I'm new to Bolt Forms so I don't know if this is possible.
I want to make to fields: State and City and when I choose one state the field City loads all the cities of that state.
It's possible?
How can I do this?

**Comment by GawainLynch** [comment]
BoltForms just uses the Symfony Forms component, and it is possible… but not easy.

Your best approach would be to use jQuery to modify the HTML `<option>` part.

**Comment by bebetodias** [comment]
My first doubt is how to prefill the fields with State and Cities.
I try to use this config in boltforms.bolt.yml:
fields:
...
city:
      type: choice
      options:
        required: false
        label: false
        choices: []            #Use no options and fill them with jQuery
        multiple: false

But, this way, the form send me an error: "Invalid value".
I thought about create a contenttype with State and other with Cities and use the choice option: 'choices: 'contenttype::pages::title::slug', but I don't know if this is the best option.

**Comment by GawainLynch** [comment]
Closing as part of a clean up
