### ISSUE TITLE
Conditional field to predict outcome when user is filling a form

### ISSUE THREAD

**Issue by melcarthus** [bolt/boltforms#43]
Hi,

I'm looking for a way to build a form that has conditional fields, depending from the settings of this form it can have a different outcome on submit. I don't know how advanced it can get with bolt forms but I want  te make a little form where visitors can fill in a list of questions (radios) and the outcome will be which person could best help them with there questions. Is this possible? It should have to work with radio buttons only.

example 1

radio button1 equals a
radio button2 equals c
radio button3 equals e

submit

outcome

person A

example 2

radio button1 equals e
radio button2 equals b
radio button3 equals b

submit

outcome

person C

I hope i have been clear enough for you to understand what I want. It's not a regular form that gets send to an emailadres. But rather it post the outcome of the form.

**Comment by GawainLynch** [comment]
So I had to take time to think about this a bit. What you could do it create a simple extension that [processes data through a SUBMISSION_PROCESSOR event](https://github.com/GawainLynch/bolt-extension-boltforms#event-listeners)
```php
$this->app['dispatcher']->addListener(BoltFormsEvents::SUBMISSION_PROCESSOR,  array($this, 'myProcessor'));
```

That event happens after the Symfony Forms processing is complete and before database writes or emails happen, so for the most part it's pretty flexible in tolerating modification to the data.

**Comment by jadwigo** [comment]
sounds like it might be time for some example extensions then :smiley:

**Comment by GawainLynch** [comment]
> sounds like it might be time for some example extensions then :smiley:

:+1:

**Comment by melcarthus** [comment]
A thanks, thought as much. I will get on it.

**Comment by melcarthus** [comment]
it would be nice, if this "simple extension" could cause bolt forms to be used as a inquiry form or in my case a form that matches you to the right person.

**Comment by GawainLynch** [comment]
I don't see why not, for example (random idea)

**Which bit did you hurt?**
- [ ] Foot
- [x] Hand
- [ ] Head

You could catch that field in the `SUBMISSION_PROCESSOR` event and lookup a contenttype record based on value, extract an email address from a text field… so on and so forth.

**Comment by melcarthus** [comment]
I'll be sure to post my version on git when it is done. First as always I have to wait if my client wants to spend the time and money on this custom job, or if he just wants to make some design alterations and go with a visual table representation of the people and their skills, instead of a interactive form ;)

**Comment by GawainLynch** [comment]
Let me guess, then need [7 red lines, some with green ink, and some transparent](https://www.youtube.com/watch?v=BKorP55Aqvg)? :laughing:

**Comment by jadwigo** [comment]
(sneaky version)

```yml
  fields:
    mailto:
      type: choice
      label: "Where did it hurt"
      options:
        choices:
          "footdoctor@example.com": Feetses
          "psychologist@example.com": Feelses
          "sales@example.com": Monies
```

**Comment by melcarthus** [comment]
@GawainLynch lol @jadwigo Very sneaky, but not bad :+1:

**Comment by melcarthus** [comment]
Fyi the extension for this is now on https://psk.nl/klikgarantie

**Comment by GawainLynch** [comment]
Closing as part of a clean up. Feel free to re-open if needed.

**Comment by zomars** [comment]
Can we reopen this?

**Comment by rossriley** [comment]
We can reopen it, I'm interested in what functionality should be simplified / enhanced since as far as I can see the events allow for fairly sophisticated management of where the email notification gets sent to. eg, this would be how I envision handling the original scenario....

```php

$app['dispatcher']->addListener('boltforms.pre_email_send',  function($event) use ($app) {
    $data = $event->getFormData();
    if (isset($data['someradiobutton'])) {

        switch ($data['someradiobutton']) {
            case 'option1': $email = 'fred@example.com'; break;
            case 'option2': $email = 'joe@example.com'; break;
            default: $email = 'info@example.com'
        }

        $event->getEmailConfig()->setToEmail($email);
    }
});
```

**Comment by GawainLynch** [comment]
FYI I spen about 80 person hours trying to make this work...  You get two choices, a BoltForms tha works broadly, or not.

**Comment by rossriley** [comment]
Closed due to no feedback, feel free to reopen if it's something that can't be solved with the above pre email send event.
