### ISSUE TITLE
ajax return messages

### ISSUE THREAD

**Issue by toneffectory** [bolt/boltforms#45]
are you planning to add ajax functionality e.d. to display return messages for like errors and success?

**Comment by GawainLynch** [comment]
Planning to, yes. Having time to… that's another story :grin: 

Of course, PRs always welcome :+1:

**Comment by zomars** [comment]
I bump this! 👍

**Comment by everyx** [comment]
:+1:

**Comment by tameroski** [comment]
(°ℇ °)

**Comment by GawainLynch** [comment]
This has been implemented and will be coming in BoltForms 3.1.0 :smile:
