### ISSUE TITLE
Question: fieldsets? 

### ISSUE THREAD

**Issue by peterboorsma** [bolt/boltforms#52]
I can't find any information about fieldsets (or postfixes, prefixes) in BoltForms. I also checked the Symfony docs. 
Is there a way to add that kind of stuff in the 'fields' section in the config file?

**Comment by jadwigo** [comment]
At the moment I think that is only doable with prefix and postfix settings

**Comment by peterboorsma** [comment]
I don't think BoltForms allows 'postfix' or 'prefix'.

I do think it's better to go back to SimpleForms :)

**Comment by GawainLynch** [comment]
BoltForms assumes template use… So it comes down to Twig file inheritance/overrides… SF makes that a bit easier in the short term, but it's also limited.  Good news is that you still get both, so SF for one form, BF form another all in the one install.

**Comment by peterboorsma** [comment]
I get the template use. But with long forms (like mine) it's quite handy to sometimes add html in the config file, so you don't have to type out all formfields in the template by hand.

What I'm trying to do is adding a line of html to a specific formfield. Like:

```
<div class="boltforms-row boltforms-field">
<label for="my_formfield">My formfield</label>
<input type="text" id="my_formfield" name="my_formfield" class="field" placeholder="My formfield" />
<p>Read <a href="/mylink">this</a> for more info</p>
</div>
```

(We are beyond an 'issue' here, I know. Sorry)

**Comment by GawainLynch** [comment]
The default templates that you can extract from BoltForms [loops through the fields](https://github.com/GawainLynch/bolt-extension-boltforms/blob/v2.5.0/assets/boltforms_form.twig#L36-L44) so you could just add a conditional there and add the HTML.

I know some might disagree with me on this, but adding HTML to the YAML like this really breaks separation and seems like a slippery slope… so to speak. Also the advantage of doing thing in the Twig template itself is at that point you still have full access to the CMS data/functionality… which I know is not needed specifically for your example, but isn't much of a jump :grin:

**Comment by peterboorsma** [comment]
I understand your viewpoint. But when creating forms, it's a lot of work to make them. And if you change your form, you also have to check your form template... 
My point is: I understand your way of thinking but as a user BoltForms, forms are hard to build and maintain.

BTW I solved my initial problem with a loop index (see code below). 

```
{% if loop.index == '5'  %}
<p class="info"text</p>
{% endif %}
```

**Comment by GawainLynch** [comment]
Closing as part of a clean up of issues

**Comment by sbonardt** [comment]
I know this one is closed but...... Just for reference sake, and all the google search hits this might get:

You can add a prefix of postfix attribute to a form field like this:

'''
firstname:
      type: text
      options:
        required: true
        label: Name
        attr:
          placeholder: Your name
          prefix: '<fieldset><legend>Gegevens cursist</legend>'
        constraints: [ NotBlank, {Length: {'min': 2}} ]
'''

So if you add a prefix to the first field supposed to be in the fieldset and add the fieldopening tag, you can add a postfix attribute in the last field with the closing tag, and you have a wrapping fieldset! (off course any HTML is possible this way, also to wrap a single field)

You can specify your own custom "boltforms_form.twig" and check for existence of the prefix/postfix attribute when iterating through the fields:

{% if form[key].vars.attr.prefix is not empty %}

And "Bob's your uncle!"... 👯
