### ISSUE TITLE
Typo &  </ul> in boltforms_email.twig 

### ISSUE THREAD

**Issue by peterboorsma** [bolt/boltforms#53]
#   fields     - Field data fron the form configuration < n = m

and there's a /ul in the loop that doesn't belong there (I think)

```
{#
 # Passed in variables:
 #   fields     - Field data fron the form configuration
 #   config     - Email configuration date
 #   data       - The posted data
 #}
{% import "boltforms_macros.twig" as macros %}
<p>Hi,</p>

<p>Somebody used the form on {{ paths.currenturl }} to send you a message. The posted data is as follows:</p>
<hr>
{% for label, value in data -%}
    {%- set field = fields[label] -%}
    {%- if field.options.label|default('') is empty -%}
{{ macros.label_value(label, value) }}
    {%- else -%}
        {%- if value is iterable -%}
<p>{{ macros.label(label) -}}
        {%- for val in value -%}
{{ macros.value(val) }}
            {%- endfor -%}
</ul></p>
        {%- else %}
{{ macros.label_value(label, value) }}
        {%- endif -%}
    {%- endif -%}
{%- endfor -%}

<hr>
<em>Sent by the <a href="https://github.com/GawainLynch/bolt-extension-boltforms">BoltForms</a> extension for <a href="https://bolt.cm">Bolt</a>.</em>
```

**Comment by GawainLynch** [comment]
Typo fixed… That `{%- for val in value -%}` loop *looks* like it's just missing an indent… I'll check the tests and see.

**Comment by fadoe** [comment]
@GawainLynch Do you need a PR to remove the ul? ;-)

**Comment by GawainLynch** [comment]
@fadoe the `<ul>` doesn't need to be removed… tidied, sure, but it is added in the macro, and I suck at Twig and needed to get properly formatted text-only emails parts working.

**Comment by fadoe** [comment]
Adding the ```<ul>``` tag in the makro is bad, because as a developer I don't know it and I wonder why this ```</ul>``` tag is present.

It is not important for me, because I override this template :).

**Comment by GawainLynch** [comment]
> Adding the ```<ul>``` tag in the makro is bad

100% agreed! If you're any good with `spaceless` feel free to PR a change. Note that the master branch is being prepared for Bolt v3, and there is a `bolt-2` branch if you do :smile:

**Comment by GawainLynch** [comment]
Long since fixed I believe
