### ISSUE TITLE
Select with required has no empty option

### ISSUE THREAD

**Issue by SahAssar** [bolt/boltforms#54]
If you give a `type: choice` a required attribute it has no empty `option`, which makes it invalid HTML.

> The first child option element of a select element with a required attribute and without a multiple attribute, and whose size is “1”, must have either an empty value attribute, or must have no text content.

http://www.w3.org/TR/html-markup/select.html

**Comment by jadwigo** [comment]
wow :eyes: 

that is a requirement that only makes sense from a technical standpoint - if you have only one option and are required to make a choice there must be the option to not choose the single option

this scenario should just be rewritten to a single checkbox element which would make sense for actual humans (either automagically by boltforms or by the person creating the form) 
that way the html will be correct, and the form will make sense

**Comment by GawainLynch** [comment]
So should we do something about this, or not?

**Comment by jadwigo** [comment]
I guess not - we can basically tell a developer that he/she should not this.

If you need a checkbox, use a checkbox, don't use a select.

To enable multiple checkboxes in select fields in boltforms you might need to add something like the following to `boltforms_custom.twig`

```twig
{%- block choice_widget_expanded -%} 
    <div {{ block('widget_container_attributes') }}> 
        {%- for child in form %} 
            {% if child.vars.value in value %} 
                {{- form_widget(child, {'checked': true}) -}} 
            {% else %} 
                {{- form_widget(child) -}} 
            {% endif %} 
            {{- form_label(child, null, {translation_domain: choice_translation_domain}) -}} 
        {% endfor -%} 
    </div> 
{%- endblock choice_widget_expanded -%} 
 
{%- block checkbox_widget -%} 
    <input type="checkbox" {{ block('widget_attributes') }}{% if value is defined %} value="{{ value }}"{% endif %}{% if checked %} checked="checked"{% endif %} /> 
{%- endblock checkbox_widget -%} 
```

**Comment by GawainLynch** [comment]
OK … I'll close this then as part of today's clean up.

@SahAssar if you disagree, or even better have a workable solution, I have zero problems with you re-opening this … just not sure how to tackle it beyond what @jadwigo is suggesting
