### ISSUE TITLE
dynamic to_email config

### ISSUE THREAD

**Issue by pasblin** [bolt/boltforms#56]
How can i change this parameter dynamic on presubmit event? ? i want send an email selecting email from choice field.
Regards

**Comment by GawainLynch** [comment]
Not currently possible, although it would be good to implement.

**Comment by pasblin** [comment]
it would be great, It would be possible to implement it in the next version?

**Comment by GawainLynch** [comment]
I think so, having a look right now as it piqued my interest :grin:

**Comment by pasblin** [comment]
jaja cool ;)

**Comment by GawainLynch** [comment]
OK, so I have [a branch](https://github.com/GawainLynch/bolt-extension-boltforms/compare/feature/email-event?expand=1) but it isn't yet tested, nor have I had the time to write tests… so still a little away from merge/tag… But feel free to try it out if your strong in the ways of git-fu :grin: 

Basically the `EmailConfig` class now has setters for all of the address fields, and there is an `BoltFormsEvents::PRE_EMAIL_SEND` event fired that contains `EmailConfig`, `FormConfig`, and `FormData` objects.

**Comment by pasblin** [comment]
Installed and working thx ;)

**Comment by GawainLynch** [comment]
Awesome! That is really helpful, thank you! :+1:
