### ISSUE TITLE
Boltforms returns success even if mail isn't delivered to smtp server

### ISSUE THREAD

**Issue by cathelijne** [bolt/boltforms#57]
To reproduce:

Configure bolt to use a local smtp server
Turn off smtp service
Fill out form and submit

Boltforms will happily return a 'message is successfully sent' message, even though below that, bolt itself will return swiftmailer errors. These, however, will be below the fold for many users, leaving them to think their form was submitted successfully.

Screenshots included. Success Message in Dutch, but you'll get the picture ;)

<img width="1638" alt="screen shot 2015-12-25 at 17 34 18" src="https://cloud.githubusercontent.com/assets/3843328/12003794/835458fa-ab2e-11e5-8d5a-37cb09895f14.png">

<img width="1626" alt="screen shot 2015-12-25 at 17 34 39" src="https://cloud.githubusercontent.com/assets/3843328/12003793/83527e9a-ab2e-11e5-962e-24971608b755.png">

**Comment by GawainLynch** [comment]
> Screenshots included. Success Message in Dutch, but you'll get the picture ;)

Dutch is OK, now that I have been living here a week :grin: 

Curious though, how/are Bolt's [mailoptions](https://github.com/bolt/bolt/blob/release/2.2/app/config/config.yml.dist#L314-L328) configured?

**Comment by cathelijne** [comment]
Hehe :) Goed!

Here's my mailoptions. I should mention that this is a VPS that I have root on. So disabling postfix is easy to do ;)

mailoptions:
  transport: smtp
  spool: true
  host: localhost
  port: 25
  encryption: null
  auth_mode: null

Merry Christmas!

**Comment by GawainLynch** [comment]
> Merry Christmas!

Hope your Christmas was a good one, and 2016 is full of awesome.

>  I should mention that this is a VPS that I have root on. So disabling postfix is easy to do 

I like the way you work! :+1: 

OK… this should be easy for you to fix.
```yaml
mailoptions:
  transport: smtp
  spool: false
   …
```

The "problem" is that `spool: true` causes Swiftmailer to delay sending emails until a `finish()` [middleware event in the Silex service provider](https://github.com/silexphp/Silex/blob/1.3/src/Silex/Provider/SwiftmailerServiceProvider.php#L95)

As such, Swiftmailer will return a `true` response to the caller, BoltForms in this case, when the message is queued, and that's the last we know of it.

**Comment by cathelijne** [comment]
Ah I see. Which is also why the page is buit as it is: success for queuing, then a fail from boltcore. Gotcha.

Will change the spool: option to false. 

And ehhh, may I suggest documenting this somewhere? :innocent:

**Comment by cathelijne** [comment]
> Hope your Christmas was a good one, and 2016 is full of awesome.

Couldn't have said that better myself! Likewise!

**Comment by sebastiaanfranken** [comment]
> And ehhh, may I suggest documenting this somewhere? 
Yes please! I'm a customer at TransIP, and I'm running bolt as well, and I have *no idea* what to set mailoptions to to get it to work. I've tried them all, and none of them seem to be working, but since it's poorly documented I can't be 100% sure.

**Comment by cathelijne** [comment]
Don't know if it's poorly documented per se. It's swiftmailer we're talking about, not bolt or the boltforms extension, and swiftmailer might have excellent documentation to explain this: http://swiftmailer.org/docs/introduction.html

That being said, since this is something we can configure with the main configuration of bolt itself, mentioning this in the bolt docs or the extension docs (but I guess it applies to simpleforms too, so the bolt docs itself would be a more logical place) would make sense.

**Comment by sebastiaanfranken** [comment]
> Don't know if it's poorly documented per se. It's swiftmailer we're talking about, not bolt or the boltforms extension, and swiftmailer might have excellent documentation to explain this: http://swiftmailer.org/docs/introduction.html

To be honest, Swiftmailers documentation is **poor**. Or I'm looking in the wrong places perhaps?

**Comment by GawainLynch** [comment]
@sebastiaanfranken generally the problem is with the host SMTP set up, especially on shared hosts.

A lot of people have success using Mandrill instead.

**Comment by sebastiaanfranken** [comment]
@GawainLynch  Sure, but I can't use Mandrill because I'm emailing semi-sensitive information and I don't want to use a 3rd party service I know nothing about.

In my opninion giving someone the advice to use a 3rd party service because the documentation isn't up-to-scratch is looking at it the wrong way around. Wouldn't it be better to make sure everybody can use this CMS/extention any way they want? It's a form/contact extention for crying out loud, it *should* be able to handle more than Mandrill...

**Comment by GawainLynch** [comment]
@sebastiaanfranken, the extension can and does do what is needed. 

The problem is **your local SMTP configuration** (Postfix, Sendmail, whatever?). I simply suggested Mandrill to people who don't possess the technical competence to handle this.

**Comment by cathelijne** [comment]
spool: false now throws a critical error when the smtp server can't be reached. While a bit crude, the message is loud and clear.
Thanks for the explanation and the updated documentation @GawainLynch :)

**Comment by GawainLynch** [comment]
@cathelijne Yeah, we can probably improve on that exception handling with the version that will accompany Bolt v3… just flat out trying to get that one out the door… and moving countries :grin:

**Comment by cathelijne** [comment]
> and moving countries :grin:

That's peanuts :grin:

**Comment by sebastiaanfranken** [comment]
I might have been a little harsh in my latest comment. Something weird is going on it seems. The extention works fine, IF I use an emailadress in the form where the TLD matches the website. Example:

The website is acme.com. If I use the contact form with me@acme.com in the form's email field (so **not** in the config!) the email gets delivered. If I use me@youtube.com the email doesn't get delivered.

I'm not sure if this is a boltforms / swiftmailer thing, or it's something on my host side (remember, this isn't running on a VPS, so I can't check logs or change config settings!) or a mixture of both. 

Anyway, thanks for the help, I've found the following link to be equally helpful in helping me setup the extention: http://symfony.com/doc/current/reference/configuration/swiftmailer.html

**Comment by GawainLynch** [comment]
Zero stress mate… It's a Monday :+1:  

Yeah, web hosting is always "fun" like that, not being able to see logs has had me pull my hair out more than once.

One thing that used to hit me was the emails ending up in a SPAM folder at the other end, I have also hit issues with host misconfiguration of SPF records.

Not suggesting it's a valid long term approach (as you have sensitive data) but if you could test with settings against an SMTP host you can get logs on, it might show quickly that there is something "interesting" going on at the provider end.

**Comment by sebastiaanfranken** [comment]
I think I've got an answer. If you use the standard boltform configs the forms "from" field gets used in the form sending logic I think (haven't checked the source yet, this is just a hunch) as the "from:" header. Something which, for unknown reasons, TransIP blocks. 

Only mails where the from header matches the TLD go through. *sigh*...

**Comment by GawainLynch** [comment]
Ugh… providers, got to love them. 

There seems to be some "interesting" assumptions that are made here for paid services like hosting and ISPs… I just ran into a port 25 block today myself… Apparently their thinking is that we can route through their poorly configured Spamassassin server and everyone is "safer".

**Comment by sebastiaanfranken** [comment]
To be honest, this is new for TransIP. Usually I can use the emailforms and their email servers fine, but they've added the requirement that all emails sent from a domain must have a matching "From:" header that matches the domain's TLD, which if you think about it, makes sense; to prevent spam from getting around through poorly-configured plugins and such.

The support is helping though, so it's not **all** bad. I've figured what I should do with their help, so that's a good thing, right?

Anyway:  does boltforms set the "From:" header, or does Swiftmailer do that? It seems to be setting the "From:" header to the value of the emailaddress used in the form itself, not to what I put in my boltforms/core config files. Maybe that's a bug?

**Comment by GawainLynch** [comment]
Yes, it set the "From:" header based on how you configure it. Not sure it makes a lot of sense for jane@doe.com to be contacting me and have her from address being gawain@bolt.cm though.

Personally I don't think it is not an assumption that the provider should be making. Enforcing the "big stick" if someone violates T&C… but they would lose my business in all of 5 seconds if they block anything I owned in this way without me having done something wrong.

**Comment by sebastiaanfranken** [comment]
The From: header isn't the only thing. If you set From: to gwain@bolt.cm and the Reply-To header to the form's email field you'll achieve the same thing. Darn, I think I just figured out a hotfix for my issue..

**Comment by jadwigo** [comment]
@GawainLynch & @sebastiaanfranken the "big stick" the provider is using here is saving you and them a lot of headaches in support...

Some bigger providers (gmail, yahoo, outlook) and spamfilters like spambayes use those headers to increase the spam score of your mail if they don't match

Since this is something relatively simple that you can configure on your end, the problem goes away if you have it configured correctly - it's nasty and messy and unclear, but the endresult is very much what you want.

**Comment by sebastiaanfranken** [comment]
@jadwigo True. But the documentation on this is **very** poor. It took me a few days and one support ticket with TransIP and an issue here (not directly, but still) plus hours of Googling to figure this out. I only found out after TransIP support nudged me in the right direction, along with a comment above.

**Comment by bobdenotter** [comment]
@sebastiaanfranken If you have thoughts on how to practically improve the docs, it'd be appreciated! 

(and PR's for docs would be even more appreciated. :-) )
