### ISSUE TITLE
uninformative "exception occurred saving submission to ContentType" 

### ISSUE THREAD

**Issue by jadwigo** [bolt/boltforms#65]
If there is an error with saving a submission to a content type all the visible information in the backend system log is "[Bolt Forms] An exception occurred saving submission to ContentType table `$contenttype`"
https://github.com/bolt/boltforms/blob/master/src/Database.php#L105

This should also show information on the frontend if debug mode for the form is on.

**Comment by GawainLynch** [comment]
Closing as part of a clean up. Feel free to re-open if needed.

This one should be well covered in the upcoming v4.
