### ISSUE TITLE
Error when I try to use reCAPTCHa (2.5.1)

### ISSUE THREAD

**Issue by gwbonline** [bolt/boltforms#66]
When I set reCAPTCHa te 'true', the form gives me an error (see screenshot). Am I doing something wrong? And is there something I have to ad to the template to display the reCAPTCHa part?
![screenshot](https://cloud.githubusercontent.com/assets/9332608/12584675/f00dc002-c448-11e5-89c2-5acd7b704905.jpg)

**Comment by bobdenotter** [comment]
Yeah, i'd advise not to use recapthca: It only works effectively against the elderly and less tech-savvy.. Spambots have no issues with recaptcha these days.

**Comment by GawainLynch** [comment]
You need to set up a [reCaptcha with Google first](https://www.google.com/recaptcha/admin#list) for the site, then add the keys to [the config](https://github.com/bolt/boltforms/blob/bolt-2/config.yml.dist#L16-L17)

**Comment by bobdenotter** [comment]
(And don't pay too much attention to my grumpy comment.. If it works well for you, that's great. :-) )

**Comment by gwbonline** [comment]
Thanks. The problem is that without the reCaptcha enabled I get tons of spam mails. When I enable it, this stops. Is there an other solution?
