### ISSUE TITLE
Inconsistent class usage

### ISSUE THREAD

**Issue by bobvandevijver** [bolt/boltforms#67]
Some classes use the base `boltform`, others `boltforms`. See [`boltforms_form.twig`](https://github.com/bolt/boltforms/blob/master/templates/boltforms_form.twig) as example. Line 57 uses `boltform`, line 67 uses `boltforms`.

This should be consistent throughout the extension. I would make a PR, except that I just started using this extension so I would probably miss a lot.

**Comment by GawainLynch** [comment]
Going though old issues :wink: 

That was actually deliberate… But @SahAssar has plans to give those default templates so loving soon on top of what I did this weekend.
