### ISSUE TITLE
Form sends each message twice

### ISSUE THREAD

**Issue by gwbonline** [bolt/boltforms#68]
I use version 2.5.1 of BoltForms. When someone uses the contact form or comment form, I get two copies of the same message. Is this some setting I set wrong? Before the update (from 2.1.4) this issue wasn't there.

**Comment by jadwigo** [comment]
have you set both a `to_email` and a `cc_email` for your form that ends up in the same mailbox?

or have you put the form in a content body of an entry somewhere and that entry is also displayed in the sidebar as well as in the main content detail page? (two forms that have the same name)

**Comment by GawainLynch** [comment]
Closing as part of a clean up.

That whole section of code has been rewritten since then, so plas feel to bug us if the bug is still bugging you :smile:
