### ISSUE TITLE
after first submitting a form, a page refresh resubmits the form

### ISSUE THREAD

**Issue by jadwigo** [bolt/boltforms#71]
If you have a boltform on a page that has no redirect and you submit a form.
If you then refresh that page, the browser usually asks if you want to resubmit the form - say yes (the default action for every popup form that normal users do), and you have resubmitted the form.

This leads to double emails, double posts, and lots of noise in your email and/or database.

The form sould either prevent double submissions by checking if it's the same as a previous submission (hard) 
or by redirecting to the result page after submission (easier)

**Comment by GawainLynch** [comment]
This presents several issues… 
* If you redirect, you loose session data.
* If you reload, you lose session data.
* if you re-submit, you may well have intended it (there is little to know way of knowing that)

**Comment by jadwigo** [comment]
1. true
2. true
3. true

But irrelevant for 99.9% of the cases. 

Session data is only relevant in multipage forms - and in those cases you don't want to rely on session data because of general unreliability because of crappy connections, varnish, nginx-apache-frankenstein servers, proxies, filters, adblockers etc.

1. you submitted a form so it has been emailed or stored - unless there is an error
2. you submitted a form so it has been emailed or stored - unless there is an error
3. a. the only real use-case I can imagine for resubmitting is developers who want to see if their changes worked - because users usually don't submit forms for themselves, they submit forms to send information to a site (owner)
3. b. if you need multiple submissions you can redirect with the relevant params, and you can build a workflow that supports it
3. c. if you intended to re-submit, you can still do that, but you'll have to re-enter the data (or have your form autofill do that) - which is nice for the site owners that don't get unintended spam

If there is an error you are returned to the form with your input - and not redirected to the result page.

Also - if you take sessiondata out of the equation xhttprequests/ajax become simpler because all that goes to the server and comes back is http post/get and html/xml/json so everything has to be explicit

So I propose to ignore all session data that is not explicitly added to the form by a site developer.

**Comment by GawainLynch** [comment]
This is over-engineering for an extension, it is an implementation detail, not a BoltForms one. 

Personally, I rely on this behaviour on some of my sites, as will others and doing this by default would break more than it fixes. If it is desired, it is doable from the template, by the implementer… BoltForms give the boolean Twig variable `sent` if it has been submitted, validated, etc…  

The extension should handle forms… the implementer should decide what is done with them.

**Comment by GawainLynch** [comment]
Long since implemented in 4.0
