### ISSUE TITLE
3 questions

### ISSUE THREAD

**Issue by Puddingboy** [bolt/boltforms#73]
For my forms (3 in total) I have a set of requirements. It speaks for itself that I intend to built them myself, but I really need to know where to go from here.

1. I need at least 1 checkbox to agree with terms of service.
2. I need 1 of my forms to be valid when 4 specific fields are empty. These are optional if they do not apply to the user. If the user decides to enter a single value, they should all be valid.
3. I need to alter the attributes of elements for my form to display properly. Where do I do this?

So far I know that I should make an extension to make this happen. I've been given [this](http://symfony.com/doc/current/book/validation.html) on validation. I've read [this](https://docs.bolt.cm/extensions/config). yet I still don't think I'm getting anywhere.

**Comment by jadwigo** [comment]
1. Add a checkbox field to your form configuration: http://symfony.com/doc/current/reference/forms/types/checkbox.html
2. I don't get what the specific requirement is? Would 4 optional fields work, or are those 4 fields dependent on another checkbox? If they are dependent on another checkbox you would have to create a custom validation for your form either in javascript or in an event handler -> https://github.com/bolt/boltforms#extending-available-events
3. In the file `app/config/extensions/boltforms.bolt.yml` you can change the options and attributes for a field https://github.com/bolt/boltforms#fields-default-values ... and you can override those in custom form templates https://github.com/bolt/boltforms#templates-for-custom-displays

**Comment by Puddingboy** [comment]
sorry if 2 came across as a little vague. the 4 fields are a set of address fields for shipping purposes. Sometimes users want their orders shipped to a different location. So I thought the simplest way to create a proper validation for this particular case would be to accept te 4 fields as valid if all of them are empty.

Am I starting to make more sense?

**Comment by jadwigo** [comment]
So if the checkbox "use a different shipping address" is checked the 4 extra address fields should all have valid non-empty data.

The quick and dirty way is a javascript validator that handles this before the `submit()` of the form.

The "correct" way would be to use an extended event for the server side validation https://github.com/bolt/boltforms#extending-available-events

**Comment by Puddingboy** [comment]
Would you suggest the quick and dirty way?

**Comment by jadwigo** [comment]
It depends if you use jquery or another library in the front-end, and it is also dependent on the structure of your form and html.

I would have to look that up, but unfortunately I don't have time to get deeper into this.
