### ISSUE TITLE
example submits indexes for choices and not values (config.yml)

### ISSUE THREAD

**Issue by Puddingboy** [bolt/boltforms#80]
Current example: `[value1, value2]`
Desired example:`{key1: 'value1', key2: 'value2'}`

Only in the last example this notation is used. Maybe it was intended for me to figure out on my own, but I can't read minds.

In my case the array notation causes only indexes to be submitted. I am not sure if this is a local issue or a general occurance.

**Comment by zomars** [comment]
Same issue here.

**Comment by zomars** [comment]
In my case, both notations print the index number instead of the value.

**Comment by GawainLynch** [comment]
This should now be fixed in master, please feel free to re-open if that is still the case.

Note that the upcoming v4 (master) uses Symfony 2.8+ style choices: `{ value1: key1, value2: key2 }`
