### ISSUE TITLE
email keeps including <p> tags

### ISSUE THREAD

**Issue by Puddingboy** [bolt/boltforms#81]
Whenever I send an email I keep getting my stuff wrapped in P tags that are not included within my twig templates. Can you help me figure out where they could be coming from? I already cleared my cache several times aswell
![](http://puu.sh/o0Kkt/439db554f1.png)
![](http://puu.sh/o0KsW/a0f075eedc.png)
![](http://puu.sh/o0KpO/d94a74908e.png)

mails as recieved in my gmail using developermode:
![](http://puu.sh/o0JGR/e7219a47d3.png)

**Comment by jadwigo** [comment]
Have you also looked at the real source of the email? 
(the link to see the source is called "Original source"  or something similar in the dropdown menu)
![image](https://cloud.githubusercontent.com/assets/1488214/14202001/c4b9e99a-f7f5-11e5-8d66-cddd488429c2.png)


Gmail might rewrite the html for display purposes - which is something boltforms cannot fix for you.

**Comment by Puddingboy** [comment]
Even the original shows that the p tags are included. I would guess that for some reason an older version of macros.twig is being used where the p tag is still included. This would explain some part.

What other information can I give you to work towards figuring out what's going on?

![](http://puu.sh/o1OV7/8c28c90cbb.png)

For security and privacy reasons I have not included the entire form.

**Comment by jadwigo** [comment]
It might be possible that another macro is loaded. In the beginning of your `partials/_boltforms.email.twig` 
it should say  `{% import "partials/_boltforms_macros.twig" as macros %}` 

The twig with hyphens `{%- something -%}` is will output less whitespace: http://twig.sensiolabs.org/doc/templates.html#whitespace-control

**Comment by Puddingboy** [comment]
Thx. Changing that first part fixed it for me. I missed that part.
