### ISSUE TITLE
I want a choice option to invalidate the field is this possible?

### ISSUE THREAD

**Issue by Puddingboy** [bolt/boltforms#82]
I have a reason to make sure users make eleborate choices rather than submitting predefined values, thus I want the first option of selectboxes to be invalid. Any ideas?

```
<opt>--</opt> <-- false and should invalidate field if picked
<opt>Yes</opt>  <-- true
<opt>No</opt>  <-- true
```

*edit: any other way than creating an empty key:value pair?

**Comment by GawainLynch** [comment]
Should now be possible with "overrides"

Closing as part of a clean up. Feel free to re-open if needed.
