### ISSUE TITLE
Notification message on different place in template

### ISSUE THREAD

**Issue by misteryyy** [bolt/boltforms#83]
Hi there, 
is there any way how to show up the notification messages out of the boltforms_form.twig template? 

I would like to use this part:

```
{% if error and app.request.get(formname) %}
    <p class="boltform-error">{{ error }}</p>
{% endif %}

{% if message and app.request.get(formname) %}
    <p class="boltform-message">{{ message }}</p>
{% endif %}
```

in my record.twig template on the different place than  {{ boltforms('myform' ) }}

Could you please help? 
Thank you, 
Josef

**Comment by GawainLynch** [comment]
You can extend all templates by copying them to your theme directory and modifying them there. If you want to update their path/name you just need to set that in `app/config/extensions/boltforms.bolt.yml`

e.g. if you want to put them in your theme directory, in a subdirectory called `misteryyy-files/`, you can just:
```yaml
my_form:
  templates:
    form: misteryyy-files/boltforms_form.twig
```

**Comment by misteryyy** [comment]
Thank you for this. I did it, but how can I take just a part of the template and use it in my other templates?  

I need to extract just the notification part and use it on other place than the rest. 
Thank you for help, 
Josef

**Comment by GawainLynch** [comment]
Closing as part of an issue clean up
