### ISSUE TITLE
No action on form?

### ISSUE THREAD

**Issue by christophermh44** [bolt/boltforms#85]
Hello,

I probably missed something inside the configuration file, but the form generated does not have any action attribute, so the page is not submitted when I click on the submit button.

I'm using Bolt 3.

Thanks for your answer :)

**Comment by bobdenotter** [comment]
If the form has no "action", it'll just be POST-ed to the current URL. If nothing happens when you click the submit button, something else might be wrong. Any custom javascript, perhaps?

**Comment by christophermh44** [comment]
Thanks for the information.
Yes, I disabled the scripts I added, seems to be working now. Thanks!
