### ISSUE TITLE
bolt 3.0.1 + boltforms 3.0.0: An exception has been thrown during the rendering of a template

### ISSUE THREAD

**Issue by psychonaut** [bolt/boltforms#86]
With bolt 3.0.1 and boltforms 3.0.0 on php 7 I've got exception:

An exception has been thrown during the rendering of a template ("Accessing type "form" by its string name is deprecated since version 2.8 and will be removed in 3.0. Use the fully-qualified type class name "Symfony\Component\Form\Extension\Core\Type\FormType" instead.") in "record.twig" at line 12.

Actually i have to replace every type in yaml, for example:

type: text 

should be changed to

type: "Symfony\Component\Form\Extension\Core\Type\TextType"

and i have to change one line in extension source to make it work:

```
--- /srv/web/blogitko/bolt3/extensions/vendor/bolt/boltforms/src/Twig/BoltFormsExtension.php.orig	2016-05-21 18:24:00.609520167 +0200
+++ /srv/web/blogitko/bolt3/extensions/vendor/bolt/boltforms/src/Twig/BoltFormsExtension.php	2016-05-21 18:24:31.189511597 +0200
@@ -72,7 +72,7 @@
             'errorCodes' => null,
         ];
 
-        $boltForms->makeForm($formName, 'form', $data, $options);
+        $boltForms->makeForm($formName, 'Symfony\Component\Form\Extension\Core\Type\FormType', $data, $options);
 
         $fields = $this->config[$formName]['fields'];
```

**Comment by GawainLynch** [comment]
Fixed in v3.0.1 :+1:
