### ISSUE TITLE
Default link to css file

### ISSUE THREAD

**Issue by evertalbers** [bolt/boltforms#91]
After installing BoltForms on Bolt 3.0, the default stylesheet link points to 
```<link href="extensions/vendor/bolt/boltforms/boltforms.css" rel="stylesheet" type="text/css" />```
but shouldn't that be an absolute link?
```<link href="/extensions/vendor/bolt/boltforms/boltforms.css" rel="stylesheet" type="text/css" />```
?

**Comment by GawainLynch** [comment]
Yep, and fixed in the upcoming BoltForms 3.1.0, but adding a /` [here](https://github.com/bolt/boltforms/blob/3.0/templates/boltforms_form.twig#L8) will work around it before I tag a release 

Thanks for reporting! :+1:
