### ISSUE TITLE
 system log: Failed Bolt Forms notification to user

### ISSUE THREAD

**Issue by isularifin** [bolt/boltforms#96]
i have upgraded my site from bolt 2.0 to 3.0. But bolt form until now couldn't send mail. then i upgrade bolt from 3.0 to 3.0.8. get same result, not sending. when i checked the system log, i got notif, "Failed Bolt Forms notification to (user)".  

Note: 
1. i am using mail options : mail
2. now i am using bolt form 3.0.2

Thanks

**Comment by GawainLynch** [comment]
BoltForms just uses the SMTP interface configured for Bolt… See [here](https://github.com/bolt/bolt/blob/release/3.0/app/config/config.yml.dist#L311-L336)

**Comment by isularifin** [comment]
thanks for the reponse @GawainLynch . i have configured smtp via zoho like this

mailoptions:
	transport: smtp
	spool: true
	host: smtp.zoho.com
	port: 465
	username: user
	password: pass
	encryption: ssl
	auth_mode: true
	senderMail: null
	senderName: null

system log was said "Sent Bolt Forms notification to user" but i have not received at all

**Comment by GawainLynch** [comment]
Is form debugging on? If so, have you set the correct email address?

**Comment by isularifin** [comment]
debug mode is false. The email adress is correct

**Comment by GawainLynch** [comment]
> debug mode is false. 

Both [here](https://github.com/bolt/boltforms/blob/master/config/config.yml.dist#L90) and [here](https://github.com/bolt/boltforms/blob/master/config/config.yml.dist#L101) ?

If both of them are false, I am at a loss … I would first try setting `spool: false` as that will return errors to the screen.

**Comment by isularifin** [comment]
i got error like this when spool is false


    Class: Twig_Error_Runtime
    Message: An exception has been thrown during the rendering of a template ("Connection could not be established with host smtp.zoho.com [Connection timed out #110]") in "form.twig" at line 13.
    Code: 0

Twig_Template->displayWithErrorHandling()
[root]//vendor/twig/twig/lib/Twig/Template.php, line 355

Twig_Template->display()
[root]//vendor/twig/twig/lib/Twig/Template.php, line 366

Twig_Template->render()
[root]//vendor/bolt/bolt/src/Response/BoltResponse.php, line 198

Bolt\Response\BoltResponse->compile()
[root]//vendor/bolt/bolt/src/Response/BoltResponse.php, line 174

Bolt\Response\BoltResponse->getContent()
[root]//vendor/symfony/http-kernel/HttpCache/Esi.php, line 131

Symfony\Component\HttpKernel\HttpCache\Esi->addSurrogateControl()
[root]//vendor/symfony/http-kernel/EventListener/SurrogateListener.php, line 49

Symfony\Component\EventDispatcher\EventDispatcher->doDispatch()
[root]//vendor/symfony/event-dispatcher/EventDispatcher.php, line 46

Symfony\Component\EventDispatcher\EventDispatcher->dispatch()
[root]//vendor/symfony/http-kernel/HttpKernel.php, line 179

Symfony\Component\HttpKernel\HttpKernel->filterResponse()
[root]//vendor/symfony/http-kernel/HttpKernel.php, line 161

Symfony\Component\HttpKernel\HttpKernel->handleRaw()
[root]//vendor/symfony/http-kernel/HttpKernel.php, line 62

Symfony\Component\HttpKernel\HttpKernel->handle()
[root]//vendor/silex/silex/src/Silex/Application.php, line 586

Silex\Application->handle()
[root]//vendor/silex/silex/src/Silex/Application.php, line 563

Silex\Application->run()
[root]//public_html/index.php, line 14

**Comment by GawainLynch** [comment]
> Connection could not be established with host smtp.zoho.com [Connection timed out #110]") 

There is your problem… your network is not allowing access to Zoho's SMTP server :smile:
