### ISSUE TITLE
[ask] field automatic generate single entry title

### ISSUE THREAD

**Issue by isularifin** [bolt/boltforms#97]
is it possible to grab tittle single entry to be value of a field in boltform like this....
<br>
![image](https://lh3.googleusercontent.com/-bh20Y7GDwXg/V4MTIMAxchI/AAAAAAAABwM/ZYfF5D0z3zkJhM7QUdij5mRKLq_ehb52gCCo/s673/text3475-1.png)

when order clicked, a field in the form generate single entry title.

if it's possible, please show me the way.

Thanks alot for the help

**Comment by GawainLynch** [comment]
Yes. See [Field(s) default values](https://github.com/bolt/boltforms/tree/3.0#fields-default-values)

An simple example would be if the form was on the "Books" ContentType record, and the field you want to fill is called `book_order` you would do something like:

```
{{ boltforms('orders', defaults={book_order: record.title}) }}
```

**Comment by isularifin** [comment]
i'll try. Thanks alot

**Comment by melcarthus** [comment]
Works like a charm, handy feature!

**Comment by GawainLynch** [comment]
@melcarthus you're going to love some of the upcoming tweaks then … :wink:
