### ISSUE TITLE
Key "datepublish" in object with ArrayAccess of class [...] does not exist

### ISSUE THREAD

**Issue by dantleech** [bolt/boltforms#98]
On the 3.0 branch, I get this error in the sent mail:

```
...
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: 8bit

Key "datepublish" in object with ArrayAccess of class 
"Bolt\Extension\Bolt\BoltForms\Config\FormConfigSection" does not exist
```

Removing this line "fixes" the issue: https://github.com/bolt/boltforms/blob/3.0/src/Database.php#L94

**Comment by GawainLynch** [comment]
Fixed in 5c4c89668e4dcce753aaa0bd082ad163a61e9fb4 and release as 3.0.3
